image: python:3.9-slim

stages:
  - tasks

services:
  - name: postgres:15-alpine
    alias: postgres



variables:
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: password
  POSTGRES_HOST_AUTH_METHOD: trust

  DBNAME: postgres
  DBHOST: postgres
  DBPORT: 5432
  DBUSER: postgres
  DBPASSWORD: password

  PROJECT_DIR: ${CI_PROJECT_DIR}
  SCRIPTS_DIR: ${PROJECT_DIR}/scripts
  TESTS_DIR: ${PROJECT_DIR}/tests
  UTILS_DIR: ${PROJECT_DIR}/utils
  PYPSQL: ${UTILS_DIR}/pypsql.py

  NO_COLOUR: '\033[0m'
  LIGHT_RED: '\033[1;31m'


.setup:
  before_script:
    - pip install -r ${PROJECT_DIR}/requirements.txt > /dev/null 2> /dev/null


tasks from 3rd to 5th:
  stage: tasks
  extends:
    - .setup
  script:
    - echo -e "${LIGHT_RED}>>> Task 3 <<<${NO_COLOUR}"
    - python3 ${PYPSQL} --file="${SCRIPTS_DIR}/ddl.sql"

    - echo -e "${LIGHT_RED}>>> Task 4-5 <<<${NO_COLOUR}"
    - python3 ${PYPSQL} --file="${SCRIPTS_DIR}/inserts.sql"
    - echo "Table 'laboratory' contains rows:"
    - python3 ${PYPSQL} --sql="SELECT * FROM laboratory" --verbose
    - echo "Table 'research' contains rows:"
    - python3 ${PYPSQL} --sql="SELECT * FROM research" --verbose
    - echo "Table 'virus' contains rows:"
    - python3 ${PYPSQL} --sql="SELECT * FROM virus" --verbose
    - echo "Table 'animal' contains rows:"
    - python3 ${PYPSQL} --sql="SELECT * FROM animal" --verbose
    - echo "Table 'task' contains rows:"
    - python3 ${PYPSQL} --sql="SELECT * FROM task" --verbose
    - echo "Table 'employee' contains rows:"
    - python3 ${PYPSQL} --sql="SELECT * FROM employee" --verbose
    - echo "Table 'personal_information' contains rows:"
    - python3 ${PYPSQL} --sql="SELECT * FROM personal_information" --verbose
    - echo "Table 'zoo' contains rows:"
    - python3 ${PYPSQL} --sql="SELECT * FROM zoo" --verbose
    - echo "Table 'history_of_task' contains rows:"
    - python3 ${PYPSQL} --sql="SELECT * FROM history_of_task" --verbose
    - SCRIPT_PATH="${SCRIPTS_DIR}/select_all.sql" pytest ${TESTS_DIR}/test_select_count.py
